import type { NextPage } from "next";
import React,{useState} from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faBars ,faXmark} from '@fortawesome/free-solid-svg-icons'
const Home: NextPage = () => {
  const [nav,setNav]= useState(false)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <section className="lg:py-4 lg:px-8 lg:bg-[#f1f1f1] lg:w-full lg:h-[100vh]">
      <nav className="lg:flex lg:items-center lg:justify-between bg-green-700 p-4 lg:bg-white">
        <div className="flex justify-between py-2 px-3">
          <h1 className="lg:text-green-700 text-white font-[500]">Logo</h1>
         <div className="lg:hidden" onClick={()=>setNav(!nav)}>
          {nav? <FontAwesomeIcon className="w-5 lg:text-green-700 text-white" icon={faXmark}/>: <FontAwesomeIcon className="w-5 lg:text-green-700 text-white" icon={faBars}/>}
        
         
         </div>
        </div>
        <ul className={!nav?"hidden":"lg:flex lg:gap-6  md:justify-between md:mt-2 md:space-y-0 md:flex md:items-center space-y-4 px-4  text-center"}>
          <li className="lg:text-green-700 text-white">Home</li>
          <li className="lg:text-green-700 text-white">How it works </li>
          <li  className="lg:text-green-700 text-white">Features</li>
          <li className="lg:text-green-700 text-white">Pricing</li>
          <li className="lg:bg-green-700 cursor-pointer lg:text-white lg:py-1 rounded text-green-700 px-2 md:my-0 md:mx-0 py-1 bg-white mx-auto md:w-32 my-0 w-52">Create Account</li>
        </ul>
      </nav>
    </section>
    </div>
  );
};

export default Home;
